# spring
server:
  port: 8082

# mongoDb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: springbankRootPsw

# security
security:
  oauth2:
    client:
      client-id: springbankClient
      client-secret: springbankSecret
      signing-key: springbankSigningKey
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      jwt.key.value: springbankSigningKey
      token-info-uri: http://localhost:8081/oauth/check_token